import Head from 'next/head'
import Avatar from '../components/3dmodel/3dmodel'
import {
  Container,
  Main,
} from '../components/sharedstyles'


export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Avatar />
      </Main>
    </Container>
  )
}
